### PR TITLE
pre loader added

### PR DESCRIPTION
**Pull request by marizvi**
Hi,
This is with reference to issue number #78 ,
I have resolved the following issue by adding pre-loader animation which will display loading animation while the loading of site in the process..
If everything is fine according to you then kindly merge my part of code.
And if anything else needed then kindly let me know anytime..

### CODE REVIEW

**Comment by manankohlii** [comment]
@marizvi hey this animation does not seem relevant to the website. Can you try adding the animation in PR #69 instead?

**Comment by marizvi** [comment]
Changes done,
Kindly look for it now..

**Comment by manankohlii** [comment]
@marizvi animation looks good but you need to make it responsive. On mobile view scroll down when loading or have a look at the ss attached. The animation should be the only thing visible on load.
Screenshot (28)

**Comment by marizvi** [comment]
Sorry for the inconvenience,
Done with the necessary changes.
Kindly have a  look on it again please.

**Comment by manankohlii** [comment]
@marizvi no worries. Looks good now, merging! Thank you for your contribution 🥇

**Pull request merged**
