### PR TITLE
custom scroll bar

### LINKED ISSUE #119: Custom scrollbar
## Describe the bug/feature
custom scroll bar for the page

@manankohlii  please assign me

### PR DESCRIPTION
**Pull request by kumarishalini6**
Fixes #119

### CODE REVIEW

**Comment by manankohlii** [comment]
@kumarishalini6 update as per changes in master.

**Comment by kumarishalini6** [comment]
@manankohlii Done now you can proceed

**Comment by kumarishalini6** [comment]
@manankohlii please have a look on this PR also

**Comment by kumarishalini6** [comment]
And this one

**Comment by manankohlii** [comment]
@kumarishalini6 can you make it thinner, and choose a slightly darker shade of yellow/orange.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
@manankohlii  now check it please

**Comment by manankohlii** [comment]
@kumarishalini6 looks good, merging! Thank you for your contribution 🥇

**Pull request merged**
