### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by vanishasamriddhi**
Footer

### CODE REVIEW

**Comment by manankohlii** [comment]
Thanks for the changes Vanisha! But I'll need some time to review them.

**Comment by manankohlii** [comment]
Hey @vanishasamriddhi the footer is too big and unnecessary at the moment, and the css is also not proper. Please make changes to the footer so that every update should be usable.

**Comment by vanishasamriddhi** [comment]
Hey @manankohlii, thank you for letting me know about the footer, I'm working on your suggestions.

**Comment by manankohlii** [comment]
Issue resolved. Closing

**Pull request closed without merging**
