### PR TITLE
Favicon added

### PR DESCRIPTION
**Pull request by marizvi**
Hi,
I have fixed this issue by adding a tab icon (favicon) as mentioned.
Kindly go through my commit if any changes required then please let me know anytime and if everything is fine then you can merge it.

### CODE REVIEW

**Comment by manankohlii** [comment]
I have checked the favicon @marizvi , there have been changes in the master branch so update accordingly then we can merge the PR.

**Comment by marizvi** [comment]
sorry, but I didn't understand, I mean what changes?
I already modified index.html file and it was working fine.

**Comment by marizvi** [comment]
ok got it,
I will be updating soon

**Comment by marizvi** [comment]
Done,
Now I think it is ready to be merged.

**Comment by manankohlii** [comment]
@marizvi merged. Thank you for your contribution 🥇

**Pull request merged**
