### PR TITLE
Added Navbar

### LINKED ISSUE #77: I would like to add a navigation bar
## Describe the bug/feature
The navigation bar will be like three line and when we will click on it the nav bar will open

## To Reproduce
I would try to add it using bootstrap

### PR DESCRIPTION
**Pull request by abhijeet141**
### Description

Fixes #77 

### Type of Change:
- New Feature

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by manankohlii** [comment]
Hello @abhijeet141 the nav bar needs to be responsive. Have a look at the screenshot and try to fix this👍🏻

**Comment by abhijeet141** [comment]
@manankohlii Kindly review the changes

**Comment by abhijeet141** [comment]
@manankohlii Is there any other changes needed ?

**Comment by manankohlii** [comment]
Yes @abhijeet141 , add a border around this and make it bolder. Something like this. And shift this to the right side of the page.
Screenshot (17)

**Comment by abhijeet141** [comment]
> Yes @abhijeet141 , add a border around this and make it bolder. Something like this. And shift this to the right side of the page.
> Screenshot (17)

okay :)

**Comment by abhijeet141** [comment]
@manankohlii made changes kindly review

**Comment by manankohlii** [comment]
@abhijeet141 this is good for now :) Thank you for your contribution 🥇

**Comment by abhijeet141** [comment]
> @abhijeet141 this is good for now :) Thank you for your contribution 🥇 

Welcome 🙂

**Pull request merged**
