### PR TITLE
Responsive Footer

### LINKED ISSUE #84: Make footer responsive
## Describe the bug/feature
The footer is not responsive for bigger screens. See screenshot attached for reference. Footer should be at the bottom.

Screenshot (6)

### PR DESCRIPTION
**Pull request by anushruti11**
### Description

The footer is now responsive for bigger screens as well.

Fixes #84 

- Bugs
- New Feature
- Documentation

### How Has This Been Tested?
On live server 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

Screenshot (1049)

### CODE REVIEW

**Comment by manankohlii** [comment]
Hello @anushruti11 this needs work, you have just fixed the footer, it should not overlap the main content and appear only when scrolled down to the bottom.
Screenshot (11)

**Comment by anushruti11** [comment]
> Hello @anushruti11 this needs work, you have just fixed the footer, it should not overlap the main content and appear only when scrolled down to the bottom.
> Screenshot (11)

Please guide me over this. Which CSS attribute should be used here for a responsive footer in screens like iPad. Although, it is responsive in the other alternatives, but for iPad screen only sticky footer works.

**Comment by anushruti11** [comment]
@manankohlii I need your guidance.

**Comment by manankohlii** [comment]
@anushruti11 waiting for mentors to be assigned to this project, you may get in touch with them. Otherwise you always have YouTube.

**Comment by anushruti11** [comment]
@shivamsingh124 can you guide me over this ?

**Comment by shivamsingh124** [comment]
https://stackoverflow.com/questions/54646939/why-is-my-positionsticky-not-working-on-ios
You should check this once if you still need any kind of guidance let me know.

**Comment by anushruti11** [comment]
> https://stackoverflow.com/questions/54646939/why-is-my-positionsticky-not-working-on-ios
> You should check this once if you still need any kind of guidance let me know.

@shivamsingh124 I tried this but it isn't working. The footer is still not responsive for iPad screen.

**Comment by shivamsingh124** [comment]
Please share the deployed link I'll check it.

**Comment by anushruti11** [comment]
> Please share the deployed link I'll check it.

https://anushruti11.github.io/spacex-launch-data/
@shivamsingh124

**Comment by anushruti11** [comment]
@shivamsingh124 Any updates?

**Comment by shivamsingh124** [comment]
Yes,
The link you gave at the time of submission and that you provided me 11 days ago are not the same (was expected to be ) previously you used fixed position so it got struck for whole page then use used sticky.
Reason it got delayed.
use Sticky providing offset from Top accordingly.
you can also achieve this with assigning value to bottom using js when it got scrolled to the bottom.
Screenshot (1155)

**Comment by shivamsingh124** [comment]
P.S. If you haven't got your answer then do describe your problem in a documented form.

**Comment by anushruti11** [comment]
> Yes,
> The link you gave at the time of submission and that you provided me 11 days ago are not the same (was expected to be ) previously you used fixed position so it got struck for whole page then use used sticky.
> Reason it got delayed.
> use Sticky providing offset from Top accordingly.
> you can also achieve this with assigning value to bottom using js when it got scrolled to the bottom.
> Screenshot (1155)

@shivamsingh124 could you please share the deployed link of this output?

**Comment by shivamsingh124** [comment]
Haven't deployed nor saved have just changed code on inspect element.
Follow the steps mentioned to get the same output.

**Pull request closed without merging**
