### PR TITLE
Button design and trigger function

### LINKED ISSUE #19: Adding trigger button functionality
I would like add the functionality of searching the mission when the Enter key is pressed.
Please assign me this issue under LGM SOC.

### LINKED ISSUE #22: Changing button design
I would like to add pointer cursor on button. Enhance Input Field and Button Design.
Add new animation to button on hover. 
Trigger function to show result as we hit enter.
Please assign me this issue under LGM SOC'21.

### PR DESCRIPTION
**Pull request by jigar-sable**
- Fixes #22 
- Fixes #19 
1. **Added better design and pointer cursor to the button with new hover animation.**
2. **Major update added trigger feature to show result as Enter key is pressed.**
3. **Updated JavaScript code to trigger button when Enter key is press.**

### CODE REVIEW

**Comment by manankohlii** [comment]
Great work @jigar-sable, thanks for your contribution 🥇 I'll wait for the core team to make the info about labels clear and then we could go on with merging the PR.

**Comment by jigar-sable** [comment]
> Great work @jigar-sable, thanks for your contribution 🥇 I'll wait for the core team to make the info about labels clear and then we could go on with merging the PR.

Thank you so much @manankohlii sir..
Sure as the labels are added.

**Comment by manankohlii** [comment]
Hello @jigar-sable there have been changes in the master branch, do update accordingly.

**Comment by jigar-sable** [comment]
> Hello @jigar-sable there have been changes in the master branch, do update accordingly.

Sure Sir.
I wanna know as card layout has been implemented do I keep the button hover animation as it is or update with my anim.
As trigger function will be added there.

**Comment by manankohlii** [comment]
@jigar-sable 👍

**Pull request merged**
