### PR TITLE
Added mission patch images (Issue #38)

### PR DESCRIPTION
**Pull request by raunak51299**
## Added mission patch images

- I added  mission patch image for each mission.

- [x] LGM-SOC'21 Participant 

Closes: #38

### CODE REVIEW

**Comment by manankohlii** [comment]
@raunak51299 I'll keep this PR open right now, waiting for website to be responsive. Keep a track for changes in the master branch!

**Comment by manankohlii** [comment]
If you'd like to work on making the website responsive let me know, I'll assign the issue to you if the already assigned is unable to do it.

**Comment by manankohlii** [comment]
@raunak51299 patches not compatible with the css. Website not responsive. Think of another way to incorporate patch or will have to keep issue on hold for now.
Screenshot (79)

**Comment by raunak51299** [comment]
> @raunak51299 patches not compatible with the css. Website not responsive. Think of another way to incorporate patch or will have to keep issue on hold for now.
> Screenshot (79)

Fixed

**Comment by manankohlii** [comment]
@raunak51299 nice! But when mission number is out of range, patch should be removed. Please fix this!
Screenshot (80)

**Comment by raunak51299** [comment]
> @raunak51299 nice! But when mission number is out of range, patch should be removed. Please fix this!
> Screenshot (80)

Done

**Comment by manankohlii** [comment]
You fixed this but now if I search for another mission after an out of range one, it doesn't show any details. Have a look and try to fix it.

**Comment by raunak51299** [comment]
> You fixed this but now if I search for another mission after an out of range one, it doesn't show any details. Have a look and try to fix it.

Fixed. sorry for these many mistakes. I'm very new to this.

**Comment by manankohlii** [comment]
No worries at all @raunak51299, this is how we learn! Quality > Quantity right? I think there's another fix needed, there should not be any space between divs when mission is out of range. Like in the current deploy, see if you can work on this and take your time :)
Screenshot (81)
Screenshot (82)

**Comment by raunak51299** [comment]
> No worries at all @raunak51299, this is how we learn! Quality > Quantity right? I think there's another fix needed, there should not be any space between divs when mission is out of range. Like in the current deploy, see if you can work on this and take your time :)
> Screenshot (81)
> Screenshot (82)

solved

**Comment by manankohlii** [comment]
@raunak51299 great! Thank you for your contribution 🥇

**Pull request merged**
