### PR TITLE
Added particles.js in background

### LINKED ISSUE #42: particles.js in background
Try to add a dynamic particles.js background with a colour related to the mission detail card structure.

### PR DESCRIPTION
**Pull request by abhijeet141**
### Description

Added particle.js in background

Fixes #42 

### Type of Change:

- New Feature

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhijeet141** [comment]
@manankohlii Please review this

**Comment by manankohlii** [comment]
Hello @abhijeet141 there are changes required. 

- Remove the background image and use black colour for particles background.
- Background not working for entire website. See attached screenshot.
- Try to make the background responsive : particles move when hovered upon or while using touch on mobile.

Screenshot (83)
.

**Comment by abhijeet141** [comment]
> Hello @abhijeet141 there are changes required.
> 
> * Remove the background image and use black colour for particles background.
> * Background not working for entire website. See attached screenshot.
> * Try to make the background responsive : particles move when hovered upon or while using touch on mobile.
> 
> Screenshot (83)
> .

Sir now background is working for entire website i will make other changes also and let you know :)

**Comment by manankohlii** [comment]
Great! @abhijeet141

**Comment by abhijeet141** [comment]
@manankohlii I have done other changes but as particles are in the background and are overlapped by other containers it is not getting hovered

**Comment by manankohlii** [comment]
No worries @abhijeet141 , this is good for now! Thanks for your contribution 🥇

**Comment by abhijeet141** [comment]
> No worries @abhijeet141 , this is good for now! Thanks for your contribution 🥇

Welcome 🙂

**Pull request merged**
