### PR TITLE
Title box border animation added...

### PR DESCRIPTION
**Pull request by marizvi**
Hi,
I have added border animation to the title box, and this animation is working absolutely fine with all mission numbers.
If everything from my contribution is fine then kindly merge my piece of code..

If there is anything else needed related to this issue kindly let me know anytime..

[ ]- My PR follows the style guidelines of this project,
[ ]- I have performed a self-review of my own code or materials,
[ ]- My changes generate no new warnings.

### CODE REVIEW

**Comment by manankohlii** [comment]
Hello @marizvi good job, but you still need to fix the margin issues. Look at the screenshots attached. When mission name is bigger, the box is touching the entire card. 
Screenshot (12)
Screenshot (13)

**Comment by marizvi** [comment]
I am happy that you liked my work,

And yes I will fix this issue, But since this margin issue wasn’t related
to this animation part, So can I generate another issue for the same or
should I fix it in this issue only?

It will be good enough if you allow me to generate another issue for this,
if not then also no problem i will fix it in this only..

**Comment by manankohlii** [comment]
@marizvi fix it in this issue only. Take your time. Quality>quantity 👍🏻

**Comment by marizvi** [comment]
Hi,
I did the changes you asked for,
Now if everything works fine then kindly merge my piece of code also.
Thank you..

**Comment by marizvi** [comment]
Sir,
It was the issue number #79.
It is still opened..

**Pull request merged**
