### PR TITLE
navbar

### LINKED ISSUE #124: fixed navbar
## Describe the bug/feature
I want to fixed navbar at top and when we slide down the color will changed

@manankohlii can i work on this issue

### PR DESCRIPTION
**Pull request by kumarishalini6**
### Description
Fixes #124

### CODE REVIEW

**Comment by manankohlii** [comment]
Not responsive

**Comment by kumarishalini6** [comment]
SpacexMK - Personal - Microsoft​ Edge 6_25_2021 10_57_39 AM

**Comment by kumarishalini6** [comment]
SpacexMK - Personal - Microsoft​ Edge 6_25_2021 11_04_42 AM
@manankohlii  now check it please

**Comment by manankohlii** [comment]
@kumarishalini6 looks the same for me. And the navbar needs to be transparent, see if you can make changes related to that.

**Pull request closed without merging**
